version: '2'
volumes:
  jenkins-data:
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
